In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

# df = pd.read_csv("../ablation_ood_results_cifar10_cifar100_1.csv")
df = pd.read_csv("../ablation_ood_results_tiny_imagenet_imagenet_r_1.csv")

In [2]:
df

,In-distribution,Out-of-distribution,Metric,ROC AUC Scores,Mean ROC AUC,Std ROC AUC,target,scaling_type,grid_size
0,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Exp,FeatureWise,5
1,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Exp,FeatureWise,5
2,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Exp,FeatureWise,5
3,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Exp,FeatureWise,5
4,tiny_imagenet,imagenet_r,multidim_scores,"[0.830596337962963, 0.8305765555555555, 0.8326128981481482, 0.8313694074074074]",0.831289,0.000829,Exp,FeatureWise,5
5,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Exp,FeatureWise,2
6,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Exp,FeatureWise,2
7,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Exp,FeatureWise,2
8,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Exp,FeatureWise,2
9,tiny_imagenet,imagenet_r,multidim_scores,"[0.8306097638888889, 0.8305971435185187, 0.8326459768518519, 0.8313708842592592]",0.831306,0.000835,Exp,FeatureWise,2
10,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Exp,FeatureWise,0
11,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Exp,FeatureWise,0
12,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Exp,FeatureWise,0
13,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Exp,FeatureWise,0
14,tiny_imagenet,imagenet_r,multidim_scores,"[0.8306910555555556, 0.8307187268518519, 0.832604212962963, 0.8314554027777779]",0.831367,0.000777,Exp,FeatureWise,0
15,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Exp,Global,5
16,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Exp,Global,5
17,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Exp,Global,5
18,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Exp,Global,5
19,tiny_imagenet,imagenet_r,multidim_scores,"[0.4171457453703704, 0.4144071111111111, 0.4310658564814815, 0.4253788055555556]",0.421999,0.006611,Exp,Global,5
20,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Exp,Global,2
21,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Exp,Global,2
22,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Exp,Global,2
23,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Exp,Global,2
24,tiny_imagenet,imagenet_r,multidim_scores,"[0.4169549907407407, 0.41421804166666665, 0.4308732083333333, 0.42519290277777777]",0.421810,0.006610,Exp,Global,2
25,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Exp,Global,0
26,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Exp,Global,0
27,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Exp,Global,0
28,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Exp,Global,0
29,tiny_imagenet,imagenet_r,multidim_scores,"[0.41560728703703703, 0.4128796157407407, 0.4295254583333333, 0.42387985648148147]",0.420473,0.006612,Exp,Global,0
30,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Beta,FeatureWise,5
31,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Beta,FeatureWise,5
32,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Beta,FeatureWise,5
33,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Beta,FeatureWise,5
34,tiny_imagenet,imagenet_r,multidim_scores,"[0.8337557083333333, 0.8349469444444445, 0.8353246666666667, 0.8340501018518518]",0.834519,0.000639,Beta,FeatureWise,5
35,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Beta,FeatureWise,2
36,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Beta,FeatureWise,2
37,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Beta,FeatureWise,2
38,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Beta,FeatureWise,2
39,tiny_imagenet,imagenet_r,multidim_scores,"[0.8337507916666665, 0.8349401064814814, 0.8353198981481482, 0.8340465462962963]",0.834514,0.000639,Beta,FeatureWise,2
40,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Beta,FeatureWise,0
41,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Beta,FeatureWise,0
42,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Beta,FeatureWise,0
43,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Beta,FeatureWise,0
44,tiny_imagenet,imagenet_r,multidim_scores,"[0.8337479629629628, 0.8349198935185185, 0.8353513657407408, 0.8340158796296296]",0.834509,0.000652,Beta,FeatureWise,0
45,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Beta,Global,5
46,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Beta,Global,5
47,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Beta,Global,5
48,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Beta,Global,5
49,tiny_imagenet,imagenet_r,multidim_scores,"[0.4145781435185185, 0.41153312499999994, 0.42883773148148147, 0.4230933333333333]",0.419511,0.006852,Beta,Global,5
50,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Beta,Global,2
51,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Beta,Global,2
52,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Beta,Global,2
53,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Beta,Global,2
54,tiny_imagenet,imagenet_r,multidim_scores,"[0.41452844907407405, 0.4114837777777778, 0.4287898055555555, 0.42304558796296293]",0.419462,0.006853,Beta,Global,2
55,tiny_imagenet,imagenet_r,TOT 1 1 (log),"[0.8355535925925925, 0.8389119074074074, 0.8367966527777777, 0.8350247337962964]",0.836572,0.001496,Beta,Global,0
56,tiny_imagenet,imagenet_r,EXC 1 1 (log),"[0.7733713819444445, 0.7730585601851852, 0.771895826388889, 0.7791369699074074]",0.774366,0.002809,Beta,Global,0
57,tiny_imagenet,imagenet_r,BAYES 1 (log),"[0.8234432407407407, 0.8290285092592593, 0.8273613865740741, 0.8215232083333334]",0.825339,0.002994,Beta,Global,0
58,tiny_imagenet,imagenet_r,Mahalanobis score,"[0.39976645601851846, 0.39667942824074076, 0.4139778194444444, 0.4085951898148148]",0.404755,0.006890,Beta,Global,0
59,tiny_imagenet,imagenet_r,multidim_scores,"[0.414278175925926, 0.4112390092592592, 0.42853571759259257, 0.42279993055555554]",0.419213,0.006850,Beta,Global,0

In [3]:
# df.sort_values(by=['Mean ROC AUC'])
df = df.drop(columns=["ROC AUC Scores"])
df = df[df["Metric"] == "multidim_scores"].sort_values(
    by="Mean ROC AUC", ascending=False
)
df = df.drop(columns=["Metric"])
df

,In-distribution,Out-of-distribution,Mean ROC AUC,Std ROC AUC,target,scaling_type,grid_size
34,tiny_imagenet,imagenet_r,0.834519,0.000639,Beta,FeatureWise,5
39,tiny_imagenet,imagenet_r,0.834514,0.000639,Beta,FeatureWise,2
44,tiny_imagenet,imagenet_r,0.834509,0.000652,Beta,FeatureWise,0
14,tiny_imagenet,imagenet_r,0.831367,0.000777,Exp,FeatureWise,0
9,tiny_imagenet,imagenet_r,0.831306,0.000835,Exp,FeatureWise,2
4,tiny_imagenet,imagenet_r,0.831289,0.000829,Exp,FeatureWise,5
19,tiny_imagenet,imagenet_r,0.421999,0.006611,Exp,Global,5
24,tiny_imagenet,imagenet_r,0.421810,0.006610,Exp,Global,2
29,tiny_imagenet,imagenet_r,0.420473,0.006612,Exp,Global,0
49,tiny_imagenet,imagenet_r,0.419511,0.006852,Beta,Global,5
54,tiny_imagenet,imagenet_r,0.419462,0.006853,Beta,Global,2
59,tiny_imagenet,imagenet_r,0.419213,0.006850,Beta,Global,0

In [4]:
df["In-distribution"] = "TinyImageNet"
df["Out-of-distribution"] = "ImageNet-R"
print(df.round(6).to_latex(float_format="%.6f", index=False))

\begin{tabular}{llrrllr}
\toprule
In-distribution & Out-of-distribution & Mean ROC AUC & Std ROC AUC & target & scaling_type & grid_size \\
\midrule
TinyImageNet & ImageNet-R & 0.834519 & 0.000639 & Beta & FeatureWise & 5 \\
TinyImageNet & ImageNet-R & 0.834514 & 0.000639 & Beta & FeatureWise & 2 \\
TinyImageNet & ImageNet-R & 0.834509 & 0.000652 & Beta & FeatureWise & 0 \\
TinyImageNet & ImageNet-R & 0.831367 & 0.000777 & Exp & FeatureWise & 0 \\
TinyImageNet & ImageNet-R & 0.831306 & 0.000835 & Exp & FeatureWise & 2 \\
TinyImageNet & ImageNet-R & 0.831289 & 0.000829 & Exp & FeatureWise & 5 \\
TinyImageNet & ImageNet-R & 0.421999 & 0.006611 & Exp & Global & 5 \\
TinyImageNet & ImageNet-R & 0.421810 & 0.006610 & Exp & Global & 2 \\
TinyImageNet & ImageNet-R & 0.420473 & 0.006612 & Exp & Global & 0 \\
TinyImageNet & ImageNet-R & 0.419511 & 0.006852 & Beta & Global & 5 \\
TinyImageNet & ImageNet-R & 0.419462 & 0.006853 & Beta & Global & 2 \\
TinyImageNet & ImageNet-R & 0.419213 & 0.006850 & Beta & Global & 0 \\
\bottomrule
\end{tabular}

In [5]:
# df = pd.read_csv("../ablation_ood_results_tiny_imagenet_imagenet_r.csv")

# # df.sort_values(by=['Mean ROC AUC'])
# df = df.drop(columns=["ROC AUC Scores"])
# df = df[df["Metric"] == "multidim_scores"].sort_values(by="Mean ROC AUC", ascending=False)
# df = df.drop(columns=["Metric"])
# df